############# English navigation ##############

# main menu
[[main]]
name = "Estimates"
url = "/estimates"
weight = 1

[[main]]
name = "Markets"
url = "/markets"
weight = 2

[[main]]
name = "People"
url = "/people"
weight = 3

[[main]]
name = "Art"
url = "/art"
weight = 4

[[main]]
name = "Other"
url = "/other"
weight = 5
